# Generated by Django 5.2.3 on 2025-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dareexchange_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dareexchange',
            old_name='deadline',
            new_name='EstimatedDate',
        ),
        migrations.RenameField(
            model_name='dareexchange',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='dareexchange',
            name='dare',
        ),
        migrations.RemoveField(
            model_name='dareexchange',
            name='email',
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='DareTitle',
            field=models.CharField(default='Untitled Dare', max_length=100),
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='Difficulty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='Tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
