# Generated by Django 5.2.3 on 2025-07-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_deadline_dareexchange_estimateddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dareexchange',
            old_name='EstimatedDate',
            new_name='Deadline',
        ),
    ]
