# Generated by Django 5.2.3 on 2025-07-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_estimateddate_dareexchange_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dareexchange',
            name='DareTitle',
            field=models.CharField(max_length=100),
        ),
    ]
