# Generated by Django 5.2.3 on 2025-07-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_dareexchange_daretitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
