# Generated by Django 5.2.3 on 2025-07-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_dareexchange_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dareexchange',
            old_name='user',
            new_name='User',
        ),
    ]
