# Generated by Django 5.2.3 on 2025-12-29 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_dareexchange_user_dareexchange_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_dares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
