# Generated by Django 5.2.3 on 2025-12-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_dareexchange_accepted_by_dareexchange_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
